pimcore:
    documents:
        doc_types:
            definitions:
                fa854a98-8948-4494-9852-63904a5aa7cc:
                    name: 'New Document Type'
                    group: null
                    controller: null
                    template: null
                    type: page
                    priority: 0
                    creationDate: 1684053078
                    modificationDate: 1684053078
                    staticGeneratorEnabled: null
